# Generated by Django 6.0.5 on 2026-05-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50, unique=True, verbose_name='Номер лицевого счёта')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма задолженности')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
            ],
            options={
                'verbose_name': 'Задолженность',
                'verbose_name_plural': 'Задолженности',
                'ordering': ['-is_paid', 'account_number'],
            },
        ),
    ]
