# Generated by Django 6.0.5 on 2026-05-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debt',
            options={'ordering': ['-last_updated', 'account_number'], 'verbose_name': 'Задолженность', 'verbose_name_plural': 'Задолженности'},
        ),
        migrations.RemoveField(
            model_name='debt',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='debt',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='debt',
            name='address',
            field=models.CharField(default='', max_length=200, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debt',
            name='last_name',
            field=models.CharField(default='', max_length=100, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debt',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
