# Generated by Django 6.0.5 on 2026-05-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_type',
            field=models.CharField(choices=[('consultation', 'Консультация'), ('service', 'Услуга'), ('complaint', 'Жалоба')], default='consultation', max_length=20, verbose_name='Тип заявки'),
        ),
    ]
