# Generated by Django 6.0.5 on 2026-05-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Слаг')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Изображение')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published_at'],
            },
        ),
    ]
