# Generated by Django 6.0.5 on 2026-05-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Содержимое'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Содержимое'),
        ),
        migrations.AddField(
            model_name='news',
            name='short_description_en',
            field=models.TextField(null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='short_description_ru',
            field=models.TextField(null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
    ]
