# Generated by Django 6.0.5 on 2026-05-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_en',
            field=models.TextField(null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_ru',
            field=models.TextField(null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название услуги'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название услуги'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название категории'),
        ),
    ]
