# Generated by Django 6.0.5 on 2026-05-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_description_en_service_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price_unit',
            field=models.CharField(blank=True, help_text='Например, "за услугу", "за месяц" и т.д.', max_length=50, null=True, verbose_name='Единица измерения цены'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
    ]
